<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Model;

use ProductComparison\Model\Base\ProductComparison as BaseProductComparison;
use Thelia\Model\Tools\ModelEventDispatcherTrait;
use Thelia\Model\Tools\PositionManagementTrait;
//use ProductComparison\Model\Tools\PositionManagementTrait;
use Propel\Runtime\Connection\ConnectionInterface;

/**
 * Class ProductComparison
 * @package ProductComparison\Model
 */
class ProductComparison extends BaseProductComparison
{
    use ModelEventDispatcherTrait;
    use PositionManagementTrait;

    public function preInsert(ConnectionInterface $con = null)
    {
        $this->setPosition($this->getNextPosition());

        return true;
    }

    protected function addCriteriaToPositionQuery($query)
    {
        $template_id = $this->getTemplateId();
        $query->filterByTemplateId($template_id);
    }
}
