<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Action;

use ProductComparison\Action\Base\ProductComparisonAction as  BaseProductComparisonAction;

/**
 * Class ProductComparisonAction
 * @package ProductComparison\Action
 */
class ProductComparisonAction extends BaseProductComparisonAction
{
}
