<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Form\Type;

use ProductComparison\Form\Type\Base\ProductComparisonIdType as BaseProductComparisonIdType;

/**
 * Class ProductComparison
 * @package ProductComparison\Form
 */
class ProductComparisonIdType extends BaseProductComparisonIdType
{
}
