<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Event\Module\Base;

/**
 * Class ProductComparisonEvents
 * @package ProductComparison\Event\Module\Base
 * @author TheliaStudio
 */
class ProductComparisonEvents
{
    const PRODUCT_COMPARISON_CREATE = "action.product_comparison.create";
    const PRODUCT_COMPARISON_UPDATE = "action.product_comparison.update";
    const PRODUCT_COMPARISON_DELETE = "action.product_comparison.delete";
    const PRODUCT_COMPARISON_UPDATE_POSITION = "action.product_comparison.update_position";
}
