<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Event;

use ProductComparison\Event\Base\ProductComparisonEvent as BaseProductComparisonEvent;

/**
 * Class ProductComparisonEvent
 * @package ProductComparison\Event
 */
class ProductComparisonEvent extends BaseProductComparisonEvent
{
}
