<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Event;

use ProductComparison\Event\Base\ProductComparisonEvents as BaseProductComparisonEvents;

/**
 * Class ProductComparisonEvents
 * @package ProductComparison\Event
 */
class ProductComparisonEvents extends BaseProductComparisonEvents
{
}
