<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Form\Base;

use ProductComparison\Form\ProductComparisonCreateForm as ChildProductComparisonCreateForm;
use ProductComparison\Form\Type\ProductComparisonIdType;

/**
 * Class ProductComparisonForm
 * @package ProductComparison\Form
 * @author TheliaStudio
 */
class ProductComparisonUpdateForm extends ChildProductComparisonCreateForm
{
    const FORM_NAME = "product_comparison_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", ProductComparisonIdType::TYPE_NAME)
        ;
    }
}
