<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Form\Base;

use ProductComparison\ProductComparison;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class ProductComparisonCreateForm
 * @package ProductComparison\Form\Base
 * @author TheliaStudio
 */
class ProductComparisonCreateForm extends BaseForm
{
    const FORM_NAME = "product_comparison_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addFeatureIdField($translationKeys, $fieldsIdKeys);
        $this->addTemplateIdField($translationKeys, $fieldsIdKeys);
    }

    protected function addFeatureIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("feature_id", "integer", array(
            "label" => $this->translator->trans("feature_id", [], ProductComparison::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("feature_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addTemplateIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("template_id", "integer", array(
            "label" => $this->translator->trans("template_id", [], ProductComparison::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("template_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "feature_id" => "product_comparison_feature_id",
            "template_id" => "product_comparison_template_id",
            "position" => "product_comparison_position",
        );
    }
}
