<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Loop;

use ProductComparison\Loop\Base\ProductComparison as BaseProductComparisonLoop;

/**
 * Class ProductComparison
 * @package ProductComparison\Loop
 */
class ProductComparison extends BaseProductComparisonLoop
{
    /**
     * You may now add your own logic
     */
}
