<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Form;

use ProductComparison\Form\Base\ProductComparisonUpdateForm as BaseProductComparisonUpdateForm;

/**
 * Class ProductComparisonUpdateForm
 * @package ProductComparison\Form
 */
class ProductComparisonUpdateForm extends BaseProductComparisonUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "feature_id" => "feature_id",
            "template_id" => "template_id",
            "position" => "position",
        );
    }
}
