<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Form;

use ProductComparison\Form\Base\ProductComparisonCreateForm as BaseProductComparisonCreateForm;

/**
 * Class ProductComparisonCreateForm
 * @package ProductComparison\Form
 */
class ProductComparisonCreateForm extends BaseProductComparisonCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "feature_id" => "Feature id",
            "template_id" => "Template id",
        );
    }
}
