<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Loop\Base;

use Propel\Runtime\ActiveQuery\Criteria;
use Thelia\Core\Template\Element\BaseLoop;
use Thelia\Core\Template\Element\LoopResult;
use Thelia\Core\Template\Element\LoopResultRow;
use Thelia\Core\Template\Element\PropelSearchLoopInterface;
use Thelia\Core\Template\Loop\Argument\Argument;
use Thelia\Core\Template\Loop\Argument\ArgumentCollection;
use Thelia\Type\BooleanOrBothType;
use ProductComparison\Model\ProductComparisonQuery;

/**
 * Class ProductComparison
 * @package ProductComparison\Loop\Base
 * @author TheliaStudio
 */
class ProductComparison extends BaseLoop implements PropelSearchLoopInterface
{
    protected $timestampable = true;

    /**
     * @param LoopResult $loopResult
     *
     * @return LoopResult
     */
    public function parseResults(LoopResult $loopResult)
    {
        /** @var \ProductComparison\Model\ProductComparison $entry */
        foreach ($loopResult->getResultDataCollection() as $entry) {
            $row = new LoopResultRow($entry);

            $row
                ->set("ID", $entry->getId())
                ->set("FEATURE_ID", $entry->getFeatureId())
                ->set("TEMPLATE_ID", $entry->getTemplateId())
                ->set("POSITION", $entry->getPosition())
            ;

            $this->addMoreResults($row, $entry);

            $loopResult->addRow($row);
        }

        return $loopResult;
    }

    /**
     * Definition of loop arguments
     *
     * example :
     *
     * public function getArgDefinitions()
     * {
     *  return new ArgumentCollection(
     *
     *       Argument::createIntListTypeArgument('id'),
     *           new Argument(
     *           'ref',
     *           new TypeCollection(
     *               new Type\AlphaNumStringListType()
     *           )
     *       ),
     *       Argument::createIntListTypeArgument('category'),
     *       Argument::createBooleanTypeArgument('new'),
     *       ...
     *   );
     * }
     *
     * @return \Thelia\Core\Template\Loop\Argument\ArgumentCollection
     */
    protected function getArgDefinitions()
    {
        return new ArgumentCollection(
            Argument::createIntListTypeArgument("id"),
            Argument::createIntListTypeArgument("feature_id"),
            Argument::createIntListTypeArgument("template_id"),
            Argument::createIntListTypeArgument('exclude_template'),
            Argument::createIntListTypeArgument("position"),
            Argument::createEnumListTypeArgument(
                "order",
                [
                    "id",
                    "id-reverse",
                    "feature_id",
                    "feature_id-reverse",
                    "template_id",
                    "template_id-reverse",
                    "manual",
                    "manual-reverse",
                ],
                "manual"
            ),
            Argument::createEnumListTypeArgument(
                "group",
                [
                    "template",
                    "feature"
                ],
                "manual"
            )
        );
    }

    /**
     * this method returns a Propel ModelCriteria
     *
     * @return \Propel\Runtime\ActiveQuery\ModelCriteria
     */
    public function buildModelCriteria()
    {
        $query = new ProductComparisonQuery();

        if (null !== $id = $this->getId()) {
            $query->filterById($id);
        }

        if (null !== $feature_id = $this->getFeatureId()) {
            $query->filterByFeatureId($feature_id);
        }

        if (null !== $template_id = $this->getTemplateId()) {
            $query->filterByTemplateId($template_id);
        }

        if (null !== $position = $this->getPosition()) {
            $query->filterByPosition($position);
        }

        $exclude_template = $this->getExcludeTemplate();
        if (null !== $exclude_template) {
            $exclude_features = ProductComparisonQuery::create()->filterByTemplateId($exclude_template)->select('feature_id')->find();

            $query
                ->filterById($exclude_features, Criteria::NOT_IN)
            ;
        }


        foreach ($this->getOrder() as $order) {
            switch ($order) {
                case "id":
                    $query->orderById();
                    break;
                case "id-reverse":
                    $query->orderById(Criteria::DESC);
                    break;
                case "feature_id":
                    $query->orderByFeatureId();
                    break;
                case "feature_id-reverse":
                    $query->orderByFeatureId(Criteria::DESC);
                    break;
                case "template_id":
                    $query->orderByTemplateId();
                    break;
                case "template_id-reverse":
                    $query->orderByTemplateId(Criteria::DESC);
                    break;
                case "manual":
                    $query->orderByPosition();
                    break;
                case "manual-reverse":
                    $query->orderByPosition(Criteria::DESC);
                    break;
            }
        }


        if (null !== $groups = $this->getGroup()) {
            foreach ($groups as $group) {
                switch ($group) {
                    case "template":
                        $query->groupByTemplateId();
                        break;
                    case "feature":
                        $query->groupByFeatureId();
                        break;
                }
            }
        }

        return $query;
    }

    protected function addMoreResults(LoopResultRow $row, $entryObject)
    {
    }
}
