<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Event\Module;

use ProductComparison\Event\Module\Base\ProductComparisonEvents as BaseProductComparisonEvents;

/**
 * Class ProductComparisonEvents
 * @package ProductComparison\Event\Module
 * @author TheliaStudio
 */
class ProductComparisonEvents extends BaseProductComparisonEvents
{
}
