<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Event\Base;

use ProductComparison\Event\Module\ProductComparisonEvents as ChildProductComparisonEvents;

/*
 * Class ProductComparisonEvents
 * @package ProductComparison\Event\Base
 * @author TheliaStudio
 */
class ProductComparisonEvents
{
    const CREATE = ChildProductComparisonEvents::PRODUCT_COMPARISON_CREATE;
    const UPDATE = ChildProductComparisonEvents::PRODUCT_COMPARISON_UPDATE;
    const DELETE = ChildProductComparisonEvents::PRODUCT_COMPARISON_DELETE;
    const UPDATE_POSITION = ChildProductComparisonEvents::PRODUCT_COMPARISON_UPDATE_POSITION;
}
