<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Controller;

use ProductComparison\Controller\Base\ProductComparisonController as BaseProductComparisonController;

/**
 * Class ProductComparisonController
 * @package ProductComparison\Controller
 */
class ProductComparisonController extends BaseProductComparisonController
{
}
