<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace ProductComparison\Action\Base;

use ProductComparison\Model\Map\ProductComparisonTableMap;
use ProductComparison\Event\ProductComparisonEvent;
use ProductComparison\Event\ProductComparisonEvents;
use ProductComparison\Model\ProductComparisonQuery;
use ProductComparison\Model\ProductComparison;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;
use Propel\Runtime\ActiveQuery\ModelCriteria;
use Propel\Runtime\ActiveQuery\PropelQuery;
use Propel\Runtime\ActiveQuery\Criteria;




/**
 * Class ProductComparisonAction
 * @package ProductComparison\Action
 * @author TheliaStudio
 */
class ProductComparisonAction extends BaseAction implements EventSubscriberInterface
{

    public function create(ProductComparisonEvent $event)
    {
        $this->createOrUpdate($event, new ProductComparison());
    }

    public function update(ProductComparisonEvent $event)
    {
        $model = $this->getProductComparison($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(ProductComparisonEvent $event)
    {
        $this->getProductComparison($event)->delete();
    }

    protected function createOrUpdate(ProductComparisonEvent $event, ProductComparison $model)
    {
        $con = Propel::getConnection(ProductComparisonTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $featureId = $event->getFeatureId()) {
                $model->setFeatureId($featureId);
            }

            if (null !== $templateId = $event->getTemplateId()) {
                $model->setTemplateId($templateId);
            }

            if (null !== $position = $event->getPosition()) {
                $model->setPosition($position);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setProductComparison($model);
    }

    protected function getProductComparison(ProductComparisonEvent $event)
    {
        $model = ProductComparisonQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'product_comparison' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function updatePosition(UpdatePositionEvent $event)
    {
        $this->genericUpdatePosition(new ProductComparisonQuery(), $event);
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            ProductComparisonEvents::CREATE => array("create", 128),
            ProductComparisonEvents::UPDATE => array("update", 128),
            ProductComparisonEvents::DELETE => array("delete", 128),
            ProductComparisonEvents::UPDATE_POSITION => array("updatePosition", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".product_comparison_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".product_comparison_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".product_comparison_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".product_comparison_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
